pipeline:
  name: Shiva
  identifier: Shiva
  projectIdentifier: ShivaP
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1699231710767
        repoName: arvinda07/go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: simple
        identifier: simple
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "welcome to harness"
