pipeline:
  identifier: Build_go_pipeline_sample_1693792638616
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: basictesting
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1693792530350
        repoName: arvinda07/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: first run
                  spec:
                    shell: Sh
                    command: echo "welcome to harness"
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
